apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: rsenvcomp
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: rsenvcomp
    app.kubernetes.io/part-of: rsenvapp
  name: rsenvcomp
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: rsenvcomp
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: rsenvcomp
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rs-demos-salp-tenant/rsenvapp/rsenvcomp@sha256:f4027e1d3fc994a3cd88d5a3d9398156c3a74ee029a556264c09ed9d3bf8cffb
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
